### ISSUE TITLE
input_dim seems not to be enough for input

### ISSUE THREAD

**Issue by katomaso** [mineshmathew/char_rnn_karpathy_keras#1]
Hi,
when I try to run your code I get an exception (included below). Under which circumstances it is actually runable?

Exception: When using TensorFlow, you should define explicitly the number of timesteps of your sequences.
If your first layer is an Embedding, make sure to pass it an "input_length" argument. Otherwise, make sure the first layer has an "input_shape" or "batch_input_shape" argument, including the time axis. Found input shape at layer lstm_1: (None, None, 39)

**Comment by mineshmathew** [comment]
@katomaso I use Theano as the backend. And there #timesteps (or length of input sequence) need not be explicitly mentioned; ie only inputDim is needed. I am not sure  how TensorFlow handles this.
