### ISSUE TITLE
Size of input text file causes memory failure during vectorization

### ISSUE THREAD

**Issue by cjsweeney** [mineshmathew/char_rnn_karpathy_keras#3]
Hi,
While running this model on a 109.5 MB text corpus, the code throws a memory error on this line:

> X = np.zeros((len(sentences), maxlen, len(chars)), dtype=np.bool)

How can I work around this restraint?
Thank you.

**Comment by mineshmathew** [comment]
You may want read only a 'batch' of training samples from your disk at a time. This one is essentially reading the entire data into a numpy array.
